# GitHub Secret Scanning Configuration
# This file helps GitHub detect custom secret patterns in your repository

version: "1"

# Custom patterns to detect
patterns:
  # Custom API Keys
  - name: Custom API Key Pattern
    regex: '(?i)(api[_-]?key|apikey)\s*[:=]\s*["\']?([a-zA-Z0-9_\-]{32,})["\']?'
    confidence: high
    
  # Private Keys
  - name: Private Key
    regex: '-----BEGIN (RSA|EC|OPENSSH|DSA|PGP) PRIVATE KEY-----'
    confidence: high
    
  # JWT Tokens
  - name: JWT Token
    regex: 'eyJ[a-zA-Z0-9_-]*\.eyJ[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*'
    confidence: medium
    
  # Database Connection Strings
  - name: Database Connection String
    regex: '(?i)(mongodb|mysql|postgresql|postgres)://[^\s]+'
    confidence: high
    
  # Generic Secrets
  - name: Generic Secret
    regex: '(?i)(secret|password|passwd|pwd)\s*[:=]\s*["\']([^"\'\s]{8,})["\']'
    confidence: medium
    
  # Blockchain Private Keys (hex format)
  - name: Blockchain Private Key
    regex: '(?i)(private[_-]?key|privkey)\s*[:=]\s*["\']?([a-fA-F0-9]{64})["\']?'
    confidence: high
    
  # Google Cloud API Keys
  - name: Google API Key
    regex: 'AIza[0-9A-Za-z_-]{35}'
    confidence: high
    
  # AWS Access Keys
  - name: AWS Access Key
    regex: 'AKIA[0-9A-Z]{16}'
    confidence: high
    
  # Slack Tokens
  - name: Slack Token
    regex: 'xox[baprs]-[0-9]{10,12}-[0-9]{10,12}-[a-zA-Z0-9]{24,32}'
    confidence: high

# Paths to exclude from scanning
exclude:
  paths:
    - "**/*.md"           # Markdown files (documentation)
    - "**/test/**"        # Test files
    - "**/tests/**"       # Test directories
    - "**/*.test.js"      # Test files
    - "**/*.spec.js"      # Spec files
    - "**/node_modules/**" # Dependencies
    - "**/dist/**"        # Build output
    - "**/build/**"       # Build output
    - "**/.env.example"   # Example env files (safe)
    - "**/package-lock.json" # Lock files
    
# Allowed secrets (false positives)
# Use with extreme caution!
allowlist:
  # Example patterns that are safe
  - 'example-api-key-not-real'
  - 'your-api-key-here'
  - 'replace-with-your-key'
  - 'test-key-12345'
  - 'dummy-secret'
  - 'placeholder'
